// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:fd772ff0-503c-4698-8971-61a9f546106f',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'smartdog-hosting-mobilehub-1591034241',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2ylwmfzzmdr11.cloudfront.net',
    'aws_mobile_analytics_app_id': 'd6753a521949428eac644fe000d7ba9a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f09d4e78-8cb3-41a9-b729-4404631980ea',
    'aws_project_name': 'smartDog-2018-04-28-23-43-59',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'smartdog-mobilehub-1591034241',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'smartdog-userfiles-mobilehub-1591034241',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_6RKdx32yO',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4gkgj8qnp54qluimci6ik4vk1p',
}

export default awsmobile;
